name: Testing needs
env:
  SAMPLE_VAR: this is a sample var
on: 
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello this is the step one"
  job2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This is the second step"
  job3:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This will onlr run after step1 and step2 has finished execution"
      - run: sleep 2
    needs:
      - step1
      - step2
  job4:
    runs-on: ubuntu-24.04
    steps:
      - name: "SEER"
        run: echo "This is the final step and the runs only after third step has finished executing"
      - name: "Second step in Job 4"
        run: echo "This is the variable we defined above $SAMPLE_VAR"
    needs: 
      - step3