name: Testing needs
on: 
  push:
    branches:
      - "main"
jobs:
  step1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello this is the step one"
  step2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This is the second step"
  step3:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This will onlr run after step1 and step2 has finished execution"
      - run: sleep 2
    needs:
      - step1
      - step2
  step4:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "This is the final step and the runs only after third step has finished executing"
    needs: 
      - step3